services:
  # Backend API (Python/FastAPI)
  - type: web
    name: news-aggregator-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m spacy download nl_core_news_lg
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: .
      - key: MISTRAL_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: LOG_LEVEL
        value: INFO
      - key: FRONTEND_ORIGINS
        value: https://news-aggregator-frontend.onrender.com

  # Frontend (Next.js)
  - type: web
    name: news-aggregator-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://news-aggregator-backend-ae10.onrender.com
