services:
  # Backend API (Python/FastAPI)
  - type: web
    name: news-aggregator-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: MISTRAL_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: LOG_LEVEL
        value: INFO

  # Frontend (Next.js)
  - type: web
    name: news-aggregator-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        # Update this after backend is deployed
        value: https://news-aggregator-backend.onrender.com
