import React from "react";
import { render, screen } from "@testing-library/react";

import { ClusterGrid } from "@/components/ClusterGrid";
import { ArticleList } from "@/components/ArticleList";
import { InsightsFallback } from "@/components/InsightsFallback";
import type { Cluster, EventArticle } from "@/lib/api";

jest.mock("framer-motion", () => ({
  __esModule: true,
  motion: new Proxy(
    {},
    {
      get: () =>
        // eslint-disable-next-line react/display-name
        ({ children, ...rest }: { children: React.ReactNode }) => <div {...rest}>{children}</div>,
    },
  ),
}));

jest.mock("@/lib/api", () => {
  const actual = jest.requireActual("@/lib/api");
  return {
    ...actual,
    getArticleBias: jest.fn().mockResolvedValue(null),
  };
});

afterEach(() => {
  jest.clearAllMocks();
});

const sampleClusters: Cluster[] = [
  {
    label: "Politieke reactie",
    summary: "Analyse van politieke reacties.",
    sources: [
      { title: "NOS", url: "https://nos.nl", spectrum: "mainstream" },
      { title: "De Correspondent", url: "https://decorrespondent.nl", spectrum: "links" },
    ],
  },
];

const sampleArticles: EventArticle[] = [
  {
    id: 1,
    title: "Artikel",
    url: "https://example.com",
    source: "NOS",
    spectrum: "mainstream",
    published_at: "2025-10-01T07:00:00Z",
  },
];

describe("ClusterGrid", () => {
  it("renders fallback when no clusters available", () => {
    render(<ClusterGrid clusters={[]} />);

    expect(screen.getByText(/nog geen invalshoeken/i)).toBeInTheDocument();
  });

  it("renders cluster cards when data provided", () => {
    render(<ClusterGrid clusters={sampleClusters} />);

    expect(screen.getByText("Politieke reactie")).toBeInTheDocument();
    expect(screen.getByText("Analyse van politieke reacties.")).toBeInTheDocument();
  });
});

describe("ArticleList", () => {
  it("renders empty state when there are no articles", () => {
    render(<ArticleList articles={[]} />);

    expect(screen.getByText(/Nog geen artikelen gekoppeld/i)).toBeInTheDocument();
  });

  it("renders article rows with spectrum badge", async () => {
    render(<ArticleList articles={sampleArticles} />);
    // Bias lookup resolves asynchronously and then shows the placeholder badge
    await screen.findByTitle("Bias analyse niet beschikbaar");

    const link = screen.getByRole("link", { name: /Artikel/ });
    expect(link).toHaveAttribute("href", "https://example.com");
    expect(screen.getByText("Mainstream")).toBeInTheDocument();
  });
});

describe("InsightsFallback", () => {
  it("explains that insights are generated by the ingest pipeline", () => {
    render(<InsightsFallback eventId={42} />);

    expect(screen.getByText(/Insights ontbreken/i)).toBeInTheDocument();
    expect(screen.queryByRole("button")).not.toBeInTheDocument();
  });

  it("shows a custom reason when provided", () => {
    render(<InsightsFallback eventId={42} reason="Kon insights niet laden." />);

    expect(screen.getByText("Kon insights niet laden.")).toBeInTheDocument();
  });
});
